spring.datasource.url=postgresql://expense_db_h4ft_user:b4vAmFfnZ3IPWrQTAUTdNCTc7V95n69q@dpg-d7jtffpj2pic73cm25mg-a.singapore-postgres.render.com/expense_db_h4ft
spring.datasource.username=expense_db_h4ft_user
spring.datasource.password=b4vAmFfnZ3IPWrQTAUTdNCTc7V95n69q

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true