SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-xxxx-a.singapore-postgres.render.com:5432/expense_db_h4ft?sslmode=require
SPRING_DATASOURCE_USERNAME=expense_db_h4ft_user
SPRING_DATASOURCE_PASSWORD=b4vAmFfnZ3IPWrQTAUTdNCTc7V95n69q
SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true