SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-xxxx-a.singapore-postgres.render.com:5432/expense_db_h4ft?sslmode=require
spring.datasource.username=expense_db_h4ft_user
spring.datasource.password=b4vAmFfnZ3IPWrQTAUTdNCTc7V95n69q
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true